backend:
  name: github
  repo: ae-ci-tbr/aecllcsite
  branch: main
  base_url: https://aecelectricbr.com
  auth_endpoint: /api/auth
  use_graphql: true

media_folder: "images/uploads"        # Where images get saved in the repo
public_folder: "/images/uploads"      # How the CMS accesses the image URL
media_library:
  name: "default"
  media_folder: "images/uploads"
  public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "index"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }

      - label: "Projects"
        name: "projects"
        file: "projects.html"
        fields:
          - { label: "Projects", name: "body", widget: "markdown" }

      - label: "Contact Page"
        name: "contact"
        file: "contact.html"
        fields:
          - { label: "Form", name: "body", widget: "markdown" }
