backend:
  name: github
  repo: ae-ci-tbr/aecllcsite
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

media_library:
  name: uploadcare

collections:
  - name: "pages"
    label: "Pages"
    folder: "site/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
